server:
  port: 8081
dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.47.100:2181?backup=192.168.47.101:2181,192.168.47.102:2181
  protocol:
    name: dubbo
    port: 20880