dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.47.100:2181?backup=192.168.47.101:2181,192.168.47.102:2181
  protocol:
    name: dubbo
    port: 20880
datasource:
  house:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&preferredTestQuery=select now()
    username: root
    password: root
  dbgirl:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&preferredTestQuery=select now()
      username: root
      password: root